version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - mytom:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: testingdb1
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     ports:
       - 3000:3000
   tomcat:
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 8081:8080
volumes:
   mytom:
    driver: local
